version: '3.9'
services:
  db:
    container_name: bluubidb
    image: postgres:14
    volumes:
      - bluubi-api-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    networks:
      - app-connect
    env_file:
      - .env
  # app:
  #    build: .
  #    container_name: bluubinodejs
  #    volumes:
  #      - .:/usr/src/app
  #    ports:
  #      - "3333:3333"
  #    depends_on:
  #      - db
  #    networks:
  #      - app-connect

volumes:
  bluubi-api-data:


networks:
  app-connect:
    driver: bridge

